import {initializeApp} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js';
import {getAuth,onAuthStateChanged,GoogleAuthProvider,signInWithPopup,createUserWithEmailAndPassword,signInWithEmailAndPassword,sendPasswordResetEmail,updateProfile,signOut} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import {getFirestore,collection,doc,addDoc,getDoc,updateDoc,deleteDoc,setDoc,onSnapshot,serverTimestamp,query,orderBy} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
import {firebaseConfig} from './firebase-config.js';
const $=id=>document.getElementById(id);let db,auth,uid=null,unsubscribe=null,tareas=[],practicas=[],perfil={},pomodoroId=null,pomodoroEnd=0,pomodoroRemaining=1500,respiracionId=null,respiracionEnd=0;
const tecnicas=[{id:'mapas',nombre:'🧠 Mapas mentales',descripcion:'Organiza la información mediante palabras clave, imágenes y conexiones.',pasos:'Escribe el tema central; añade ideas principales; conecta conceptos relacionados; utiliza palabras clave e imágenes.',ejemplo:'Tema: memoria → tipos → ejemplos → aplicaciones.'},{id:'cornell',nombre:'📝 Método Cornell',descripcion:'Divide tus apuntes en notas, preguntas clave y resumen para facilitar el repaso.',pasos:'Reserva una columna para preguntas, otra para notas y una franja inferior para resumir; repasa respondiendo sin mirar.',ejemplo:'Tema: célula. Pregunta: ¿Qué hace el núcleo? Responde y verifica.'},{id:'espaciada',nombre:'🔄 Repetición espaciada',descripcion:'Repasa en diferentes momentos en lugar de memorizar todo de una sola vez.',pasos:'Estudia hoy; repasa mañana; vuelve a revisar a los 3 y 7 días; ajusta según lo que recuerdes.',ejemplo:'Repasa vocabulario el lunes, martes, jueves y el siguiente lunes.'},{id:'flashcards',nombre:'🃏 Flashcards',descripcion:'Tarjetas con una pregunta por un lado y la respuesta por el otro.',pasos:'Escribe preguntas breves; intenta responder antes de voltear; repite las tarjetas que falles.',ejemplo:'Pregunta: ¿Qué es la memoria? Respuesta: Capacidad para codificar, almacenar y recuperar información.'},{id:'pomodoro',nombre:'⏱️ Técnica Pomodoro',descripcion:'Alterna períodos cortos de concentración con descansos.',pasos:'Estudia 25 minutos, descansa 5 y repite; tras varios ciclos haz una pausa más larga.',ejemplo:'25 minutos de lectura + 5 de descanso.'},{id:'activo',nombre:'📖 Repaso activo',descripcion:'Recuerda la información sin mirar tus apuntes y comprueba lo aprendido.',pasos:'Cierra tus notas, explica el tema con tus palabras, comprueba errores y vuelve a intentarlo.',ejemplo:'Explica en voz alta los pasos de un experimento sin leer.'}];
const consejos=[['¿Procrastinas mucho?','Empieza con una tarea pequeña y establece un tiempo corto para comenzar.'],['¿Tienes muchas tareas?','Haz una lista y ordénala según la fecha de entrega y prioridad.'],['¿Te distraes fácilmente?','Aleja las notificaciones y estudia en un espacio con pocas distracciones.'],['¿Te cuesta empezar a estudiar?','Establece una meta pequeña: «Estudiaré durante 20 minutos».'],['¿Te sientes estresado/a?','Haz una pausa, respira y retoma tus actividades de manera progresiva.'],['¿No sabes qué técnica utilizar?','Prueba diferentes técnicas y observa cuál se adapta mejor a tu forma de aprender.']];
function mensaje(t){$('estado').textContent=t}function error(e){console.error(e);mensaje('No se pudo completar la operación: '+(e.code||e.message||e))}function texto(el,value){el.textContent=value;return el}function node(tag,cls,value){const el=document.createElement(tag);if(cls)el.className=cls;if(value!==undefined)el.textContent=value;return el}
function pintarTecnicas(){const root=$('tecnicasLista');tecnicas.forEach(t=>{const col=node('div','col-md-6 col-xl-4'),card=node('article','card tech-card'),body=node('div','card-body');body.append(node('h3','h5',t.nombre),node('p','',t.descripcion),node('h4','h6','¿Cómo hacerlo?'),node('p','',t.pasos),node('h4','h6','Ejemplo'),node('p','',t.ejemplo));const b=node('button','btn btn-outline-primary','✓ Practiqué esta técnica');b.type='button';b.addEventListener('click',async()=>{if(!uid)return mensaje('Inicia sesión para guardar tu progreso.');b.disabled=true;try{await addDoc(collection(db,'usuarios',uid,'practicas'),{tecnica:t.id,fecha:serverTimestamp()});mensaje('Práctica registrada.')}catch(e){error(e)}finally{b.disabled=false}});body.append(b);card.append(body);col.append(card);root.append(col)})}
function pintarConsejos(){consejos.forEach(([q,a])=>{const col=node('div','col-md-6'),card=node('div','card h-100'),body=node('div','card-body');body.append(node('h3','h5','📌 '+q),node('p','mb-0',a));card.append(body);col.append(card);$('consejosLista').append(col)})}
function pintarTareas(){const root=$('tareasLista');root.replaceChildren();window.dispatchEvent(new CustomEvent('estudia:data',{detail:{tareas,practicas}}));if(!tareas.length){root.append(node('p','text-muted','Todavía no tienes tareas. Agrega la primera.'));return}const grupos=new Map();for(const t of tareas){const k=t.fecha||'Sin fecha';if(!grupos.has(k))grupos.set(k,[]);grupos.get(k).push(t)}for(const [fecha,items] of [...grupos].sort((a,b)=>a[0].localeCompare(b[0]))){root.append(node('h3','h6 mt-3',fecha));const ul=node('ul','list-group');items.forEach(t=>{const li=node('li','list-group-item d-flex align-items-center gap-2'),check=node('input','form-check-input mt-0'),label=node('span','flex-grow-1'+(t.completada?' task-done':''),t.titulo+' · '+t.tipo),del=node('button','btn btn-sm btn-outline-danger','Eliminar');check.type='checkbox';check.checked=!!t.completada;check.setAttribute('aria-label','Completar '+t.titulo);check.addEventListener('change',async()=>{check.disabled=true;try{await updateDoc(doc(db,'usuarios',uid,'tareas',t.id),{completada:check.checked})}catch(e){error(e);check.checked=!check.checked}finally{check.disabled=false}});del.type='button';del.setAttribute('aria-label','Eliminar '+t.titulo);del.addEventListener('click',async()=>{if(!confirm('¿Eliminar esta tarea?'))return;del.disabled=true;try{await deleteDoc(doc(db,'usuarios',uid,'tareas',t.id))}catch(e){error(e);del.disabled=false}});li.append(check,label,del);ul.append(li)});root.append(ul)}}
function pintarProgreso(){window.dispatchEvent(new CustomEvent('estudia:data',{detail:{tareas,practicas}}));const completadas=tareas.filter(t=>t.completada).length,usadas=new Set(practicas.map(p=>p.tecnica)).size,dias=new Set(tareas.map(t=>t.fecha).filter(Boolean)).size,sesiones=practicas.length;const root=$('estadisticas');root.replaceChildren();[['Tareas completadas',completadas],['Técnicas utilizadas',usadas],['Días planificados',dias],['Sesiones de estudio',sesiones]].forEach(([name,num])=>{const col=node('div','col-6 col-lg-3'),card=node('div','card h-100'),body=node('div','card-body');body.append(node('div','stat',String(num)),node('div','',name));card.append(body);col.append(card);root.append(col)});const logros=[['Primera tarea completada',completadas>=1],['Primera semana organizada',dias>=5],['5 tareas completadas',completadas>=5],['Primera técnica utilizada',usadas>=1],['Semana de estudio constante',new Set(practicas.map(p=>p.fecha?.toDate?.().toLocaleDateString('en-CA')).filter(Boolean)).size>=5]];$('logros').replaceChildren(...logros.map(([n,ok])=>node('p','mb-1'+(ok?'':' text-muted'),(ok?'⭐ ':'🔒 ')+n)))}
function pintarAnimos(){const opciones=[['😄','Muy bien'],['🙂','Bien'],['😐','Regular'],['😟','Preocupado/a'],['😣','Muy estresado/a']];$('animos').replaceChildren(...opciones.map(([emoji,label])=>{const b=node('button','btn '+(perfil.animo===label?'btn-primary':'btn-outline-secondary'),emoji+' '+label);b.type='button';b.addEventListener('click',async()=>{if(!uid)return mensaje('Inicia sesión para guardar tu progreso.');try{await setDoc(doc(db,'usuarios',uid,'datos','perfil'),{animo:label,actualizado:serverTimestamp()},{merge:true})}catch(e){error(e)}});return b}));$('animoActual').textContent=perfil.animo?'Último estado registrado: '+perfil.animo:'Aún no registras tu estado de ánimo.'}
$('formTarea').addEventListener('submit',async e=>{e.preventDefault();if(!uid)return mensaje('Inicia sesión para guardar tu progreso.');const b=e.currentTarget.querySelector('[type=submit]');b.disabled=true;try{await addDoc(collection(db,'usuarios',uid,'tareas'),{titulo:$('tituloTarea').value.trim(),fecha:$('fechaTarea').value,tipo:$('tipoTarea').value,completada:false,creada:serverTimestamp()});$('tituloTarea').value='';mensaje('Tarea guardada.')}catch(err){error(err)}finally{b.disabled=false}});
function reloj(){const n=Math.max(0,Math.ceil((pomodoroEnd-Date.now())/1000));pomodoroRemaining=n;$('reloj').textContent=String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');if(n===0){clearInterval(pomodoroId);pomodoroId=null;window.dispatchEvent(new Event('estudia:pomodoro-end'));mensaje('¡Terminó el Pomodoro! Toma un descanso de 5 minutos.')}}$('iniciarPomodoro').addEventListener('click',()=>{if(pomodoroId)return;pomodoroEnd=Date.now()+pomodoroRemaining*1000;pomodoroId=setInterval(reloj,250);reloj()});$('pausarPomodoro').addEventListener('click',()=>{if(!pomodoroId)return;reloj();clearInterval(pomodoroId);pomodoroId=null});$('reiniciarPomodoro').addEventListener('click',()=>{clearInterval(pomodoroId);pomodoroId=null;pomodoroRemaining=1500;$('reloj').textContent='25:00';window.dispatchEvent(new Event('estudia:pomodoro-reset'))});
function detenerRespiracion(){document.body.classList.remove('breathing');clearInterval(respiracionId);respiracionId=null;$('guiaRespiracion').textContent='Ejercicio detenido. Puedes retomarlo cuando quieras.'}$('respirar').addEventListener('click',()=>{document.body.classList.add('breathing');clearInterval(respiracionId);respiracionEnd=Date.now()+60000;const actualizar=()=>{const s=Math.max(0,Math.ceil((respiracionEnd-Date.now())/1000));if(!s){document.body.classList.remove('breathing');clearInterval(respiracionId);respiracionId=null;$('guiaRespiracion').textContent='Ejercicio terminado. Vuelve a tus actividades a tu ritmo.';return}const etapa=Math.floor((60-s)%10/5);$('guiaRespiracion').textContent=(etapa?'Exhala suavemente':'Inhala suavemente')+' · '+s+' s restantes'};actualizar();respiracionId=setInterval(actualizar,250)});$('detenerRespiracion').addEventListener('click',detenerRespiracion);
pintarTecnicas();pintarConsejos();$('fechaTarea').value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);pintarTareas();pintarProgreso();pintarAnimos();
// Autenticación obligatoria: no se crean sesiones anónimas.
const app=initializeApp(firebaseConfig);
db=getFirestore(app);
auth=getAuth(app);
const googleProvider=new GoogleAuthProvider();
const authPanel=$('authPanel'), contenido=$('contenido'), sesion=$('sesion'), authMensaje=$('authMensaje');
function avisoAuth(t,fallo=false){authMensaje.textContent=t;authMensaje.className='auth-message '+(fallo?'text-danger':'text-success')}
function explicarError(e){const mensajes={
 'auth/email-already-in-use':'Este correo ya está registrado. Inicia sesión.',
 'auth/invalid-email':'Escribe un correo electrónico válido.',
 'auth/weak-password':'La contraseña es demasiado débil.',
 'auth/invalid-credential':'Correo o contraseña incorrectos.',
 'auth/popup-closed-by-user':'Se cerró la ventana de Google.',
 'auth/popup-blocked':'Permite las ventanas emergentes para entrar con Google.',
 'auth/unauthorized-domain':'Autoriza este dominio en Firebase Authentication.',
 'auth/operation-not-allowed':'Activa este método de acceso en Firebase Authentication.',
 'auth/network-request-failed':'Comprueba tu conexión a internet.'
};return mensajes[e.code]||('No se pudo completar la operación: '+(e.code||e.message||e))}
async function asegurarPerfil(user,nombre){const ref=doc(db,'usuarios',user.uid),snap=await getDoc(ref);if(!snap.exists())await setDoc(ref,{nombre:nombre||user.displayName||'',correo:user.email||'',creadoEn:serverTimestamp()})}
function mostrarVista(user){window.dispatchEvent(new CustomEvent('estudia:user',{detail:{uid:user?.uid||null,name:user?.displayName||user?.email||''}}));document.body.classList.toggle('is-auth',!user);window.dispatchEvent(new CustomEvent('estudia:auth',{detail:{signedIn:!!user,name:user?.displayName||user?.email||''}}));document.getElementById('appNavbar').hidden=!user;document.getElementById('appFooter').hidden=!user;authPanel.hidden=!!user;contenido.hidden=!user;sesion.hidden=!user;if(user){$('usuarioActual').textContent=user.displayName||user.email||'Estudiante';mensaje('Conectado · Tu progreso se guarda en tu cuenta.')}else{mensaje('Inicia sesión para guardar y consultar tu progreso.');tareas=[];practicas=[];perfil={};pintarTareas();pintarProgreso();pintarAnimos()}}
function observarUsuario(user){if(unsubscribe){unsubscribe.forEach(fn=>fn());unsubscribe=null}uid=user?.uid||null;mostrarVista(user);if(!uid)return;unsubscribe=[onSnapshot(query(collection(db,'usuarios',uid,'tareas'),orderBy('fecha')),(snap)=>{tareas=snap.docs.map(d=>({id:d.id,...d.data()}));pintarTareas();pintarProgreso()},error),onSnapshot(collection(db,'usuarios',uid,'practicas'),snap=>{practicas=snap.docs.map(d=>d.data());pintarProgreso()},error),onSnapshot(doc(db,'usuarios',uid,'datos','perfil'),snap=>{perfil=snap.data()||{};window.dispatchEvent(new CustomEvent('estudia:profile',{detail:{perfil}}));pintarAnimos()},error)]}
onAuthStateChanged(auth,observarUsuario,e=>{avisoAuth(explicarError(e),true);error(e)});
// El cambio de modo se gestiona en auth-ui.js conservando authModo y authSubmit. 
$('authForm').addEventListener('submit',async e=>{e.preventDefault();const b=$('authSubmit'),modo=$('authModo').value,correo=$('authCorreo').value.trim(),clave=$('authClave').value,nombre=$('authNombre').value.trim();if(modo==='registro'&&!nombre)return avisoAuth('Escribe tu nombre.',true);if(!e.currentTarget.reportValidity())return;b.disabled=true;avisoAuth('Procesando…');try{if(modo==='registro'){const cred=await createUserWithEmailAndPassword(auth,correo,clave);await updateProfile(cred.user,{displayName:nombre});await asegurarPerfil(cred.user,nombre);$('usuarioActual').textContent=nombre}else{await signInWithEmailAndPassword(auth,correo,clave)}$('authClave').value='';avisoAuth('')}catch(err){avisoAuth(explicarError(err),true)}finally{b.disabled=false}});
$('entrarGoogle').addEventListener('click',async()=>{const b=$('entrarGoogle');b.disabled=true;avisoAuth('Conectando con Google…');try{const cred=await signInWithPopup(auth,googleProvider);await asegurarPerfil(cred.user);avisoAuth('')}catch(err){avisoAuth(explicarError(err),true)}finally{b.disabled=false}});
$('recuperarClave').addEventListener('click',async()=>{const correo=$('authCorreo').value.trim();if(!correo)return avisoAuth('Escribe tu correo en el campo de arriba.',true);try{await sendPasswordResetEmail(auth,correo);avisoAuth('Si el correo está registrado, recibirás instrucciones para restablecer tu contraseña.')}catch(err){avisoAuth(explicarError(err),true)}});
$('salir').addEventListener('click',async()=>{try{await signOut(auth);$('authClave').value='';location.hash='#inicio'}catch(err){error(err)}});
