(()=>{'use strict';const $=id=>document.getElementById(id);const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;let tasks=[],practices=[],uid=null,profile={},month=new Date();month.setDate(1);let selected=null,priorAchievements=new Set(),initialized=false,achievementTimer;const avatars=['👩‍🎓','👨‍🎓','🧑‍🎓','🦊','🐼','🐱','🌻','🚀','🦋','⭐'];
const safeDate=d=>/^\d{4}-\d{2}-\d{2}$/.test(d||'')?d:null;const dateKey=d=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');
const theme=localStorage.getItem('estudia-theme')==='dark'?'dark':'light';function setTheme(t){document.documentElement.dataset.theme=t;localStorage.setItem('estudia-theme',t);$('themeToggle').textContent=t==='dark'?'☀️':'🌙';$('themeToggle').setAttribute('aria-label',t==='dark'?'Activar modo claro':'Activar modo oscuro')}setTheme(theme);$('themeToggle').onclick=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');
function calendar(){const grid=$('calendarGrid');grid.replaceChildren();$('calMonth').textContent=new Intl.DateTimeFormat('es-PE',{month:'long',year:'numeric'}).format(month);['L','M','M','J','V','S','D'].forEach(x=>{const e=document.createElement('span');e.className='calendar-weekday';e.textContent=x;grid.append(e)});const offset=(month.getDay()+6)%7,days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();for(let i=0;i<offset;i++){const e=document.createElement('span');e.setAttribute('aria-hidden','true');grid.append(e)}for(let d=1;d<=days;d++){const key=dateKey(new Date(month.getFullYear(),month.getMonth(),d)),count=tasks.filter(t=>safeDate(t.fecha)===key).length,b=document.createElement('button');b.type='button';b.className='calendar-day'+(key===dateKey(new Date())?' is-today':'')+(key===selected?' is-selected':'');b.textContent=d;b.setAttribute('aria-label',`${d}: ${count} actividades`);if(count){const dot=document.createElement('span');dot.className='calendar-dot';dot.textContent=count;b.append(dot)}b.onclick=()=>{selected=key;calendar()};grid.append(b)}const matches=tasks.filter(t=>safeDate(t.fecha)===selected);$('calSelected').textContent=selected?`${selected}: ${matches.length?matches.map(t=>t.titulo+(t.completada?' ✓':'')).join(' · '):'No hay actividades para este día.'}`:'Selecciona un día para ver sus actividades.'}
$('calPrev').onclick=()=>{month.setMonth(month.getMonth()-1);calendar()};$('calNext').onclick=()=>{month.setMonth(month.getMonth()+1);calendar()};calendar();
function celebrate(message){const box=$('achievementToast');box.textContent='🎉 '+message;box.hidden=false;box.classList.remove('achievement-pop');void box.offsetWidth;box.classList.add('achievement-pop');clearTimeout(achievementTimer);achievementTimer=setTimeout(()=>box.hidden=true,4500)}
function achievements(){const done=tasks.filter(t=>t.completada).length,used=new Set(practices.map(p=>p.tecnica)).size,days=new Set(tasks.map(t=>safeDate(t.fecha)).filter(Boolean)).size;return new Map([['first',done>=1?'¡Primera tarea completada!':null],['five',done>=5?'¡Cinco tareas completadas!':null],['week',days>=5?'¡Primera semana organizada!':null],['tech',used>=1?'¡Primera técnica practicada!':null]])}
window.addEventListener('estudia:data',e=>{tasks=e.detail.tareas||[];practices=e.detail.practicas||[];calendar();const current=achievements();const achieved=new Set([...current].filter(([,v])=>v).map(([k])=>k));if(initialized){for(const [k,v] of current)if(v&&!priorAchievements.has(k)){celebrate(v);break}}priorAchievements=achieved;initialized=true});
window.addEventListener('estudia:user',e=>{uid=e.detail.uid;initialized=false;priorAchievements.clear();if(!uid){profile={};$('profileDialog').hidden=true;document.body.classList.remove('profile-open','focus-active')}});
function applyProfile(){const avatar=avatars.includes(profile.avatar)?profile.avatar:avatars[0];$('avatarSmall').textContent=avatar;$('avatarPreview').textContent=avatar;$('profileName').value=profile.nombre||$('usuarioActual').textContent||'';if(profile.nombre){$('usuarioActual').textContent=profile.nombre;const first=profile.nombre.trim().split(/\s+/)[0];$('homeGreeting').textContent='¡Hola, '+first+'! 👋';$('saludoUsuario').textContent='¡Qué bueno verte, '+first+'! ✨'}}
window.addEventListener('estudia:profile',e=>{profile=e.detail.perfil||{};applyProfile()});const choice=$('avatarChoices');avatars.forEach(a=>{const b=document.createElement('button');b.type='button';b.textContent=a;b.className='avatar-choice';b.setAttribute('aria-label','Avatar '+a);b.onclick=()=>{profile.avatar=a;$('avatarPreview').textContent=a;choice.querySelectorAll('button').forEach(x=>x.classList.toggle('chosen',x===b))};choice.append(b)});
function openProfile(){applyProfile();choice.querySelectorAll('button').forEach(x=>x.classList.toggle('chosen',x.textContent===(profile.avatar||avatars[0])));$('profileDialog').hidden=false;document.body.classList.add('profile-open');$('profileName').focus()}function closeProfile(){$('profileDialog').hidden=true;document.body.classList.remove('profile-open')}$('profileOpen').onclick=openProfile;$('profileClose').onclick=closeProfile;$('profileDialog').addEventListener('click',e=>{if(e.target===$('profileDialog'))closeProfile()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeProfile();if(document.body.classList.contains('focus-active'))exitFocus()}});
$('profileForm').addEventListener('submit',async e=>{e.preventDefault();if(!uid)return;const name=$('profileName').value.trim();if(!name)return;const btn=e.target.querySelector('[type=submit]');btn.disabled=true;$('profileStatus').textContent='Guardando…';try{const {getFirestore,doc,setDoc}=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js');const {getApp}=await import('https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js');await setDoc(doc(getFirestore(getApp()),'usuarios',uid,'datos','perfil'),{nombre:name,avatar:profile.avatar||avatars[0]},{merge:true});$('profileStatus').textContent='Perfil guardado correctamente.';celebrate('¡Perfil actualizado!')}catch(err){console.error(err);$('profileStatus').textContent='No se pudo guardar el perfil. Revisa tu conexión y las reglas de Firestore.'}finally{btn.disabled=false}});
const ring=$('focusRing');function updateRing(){const txt=$('reloj').textContent.split(':');const seconds=Number(txt[0])*60+Number(txt[1]);ring.style.setProperty('--focus-progress',Math.max(0,Math.min(100,(1500-seconds)/1500*100))+'%')};new MutationObserver(updateRing).observe($('reloj'),{childList:true,characterData:true,subtree:true});updateRing();function exitFocus(){document.body.classList.remove('focus-active');$('focusExit').hidden=true;$('focusMode').hidden=false}$('focusMode').onclick=()=>{document.body.classList.add('focus-active');$('focusExit').hidden=false;$('focusMode').hidden=true};$('focusExit').onclick=exitFocus;window.addEventListener('estudia:pomodoro-end',()=>{celebrate('¡Sesión de concentración terminada!');exitFocus()});window.addEventListener('estudia:pomodoro-reset',updateRing);
// El modo de concentración usa el temporizador existente; no crea sesiones ficticias.
})();